SELECT B.BOOK_ID,
        A.AUTHOR_NAME,
        DATE_FORMAT(STR_TO_DATE(b.PUBLISHED_DATE, '%Y-%m-%d %H:%i:%s'), '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK AS B
JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE ASC;